- hosts: all
  sudo: yes
  tasks:
    - apt: update_cache=yes
    - apt: name=python2.7
    - apt: name=node-less
    - apt: name=python-pip
    - apt: name=redis-server
    - pip: name=file:///vagrant extra_args='-e'
    - pip: name=pytest