- hosts: all
  vars_files: ['secret_vars.yml']
  sudo: yes
  tasks:
    - apt: update_cache=yes
    - apt: name=python2.7
    - apt: name=python-pip
    - apt: name=redis-server
    - pip: name=file:///vagrant extra_args='-e'
    - pip: name=pytest

    - user: name=pydrill
    - file: path=/etc/pydrill state=directory owner=pydrill
    - file: path=/var/lib/pydrill state=directory owner=pydrill
    - template: src=templates/flask_config.j2 dest=/etc/pydrill/pydrill.cfg owner=pydrill
